### ISSUE TITLE
Error while renew certificates with Certbot

### ISSUE THREAD

**Issue by acien101** [anarres-org/letsencrypt-request#1] opened 2019-05-06 15:12 UTC
```
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for drone.radio.clubs.etsit.upm.es
Cleaning up challenges
Attempting to renew cert (drone.radio.clubs.etsit.upm.es) from /etc/letsencrypt/renewal/drone.radio.clubs.etsit.upm.es.conf produced an unexpected error: [Errno 2] No such file or directory: 'systemct restart nginx'. Skipping.
The following certs could not be renewed:
  /etc/letsencrypt/live/drone.radio.clubs.etsit.upm.es/fullchain.pem (failure)
```

Caused by `defaults/main.yml`:
```
letsencrypt_renewal_conf: |
  renew_hook = {{ letsencrypt_renew_hook }}
```

That shouldn't be added to the conf file.

**Comment by m0wer** [comment] 2019-05-07 10:37
Apparently it's just a typo, but it comes from a variable not defined in this role. Check `[Errno 2] No such file or directory: 'systemct restart nginx'.`, `systemct` should be instead `systemctl`.

**Comment by m0wer** [comment] 2019-05-07 10:45
Anyways, the best option is to use `letsencrypt_renew_hook: /usr/sbin/service nginx reload` and this is needed because if we don't reload or restart nginx after renewing the certs, the change won't take place and the certificates might expire before the next manual reboot of the server or restart of the proxy service.

**Comment by m0wer** [comment] 2019-05-19 11:04
Can we close this @acien101 ?

**Comment by acien101** [comment] 2019-06-12 16:00
On `/etc/letsencrypt/renewal/hackmd.radio.clubs.etsit.upm.es.conf`:
```
# BEGIN ANSIBLE MANAGED BLOCK
renew_hook = /usr/sbin/service nginx reload
```

The ouput:

```
Cleaning up challenges
Attempting to renew cert (whiteclub.radio.clubs.etsit.upm.es) from /etc/letsencrypt/renewal/whiteclub.radio.clubs.etsit.upm.es.conf produced an unexpected error: [Errno 2] No such file or directory: '/usr/sbin/service nginx reload'. Skipping.
```

Solution: delete `renew_hook` variable from  `/etc/letsencrypt/renewal/hackmd.radio.clubs.etsit.upm.es.conf`

**Comment by m0wer** [comment] 2019-06-12 16:20
@acien101 it's not a bug, it's a feature xD We need the services that use the cert to be restared/reloaded on a successful renewal so removing it is not an option. The problem is that the var `renew_hook` should be in the `[renewalparams] ` section instead of  in the `[[webrootmap]]` one. I'll get to it right now.

**Closed** 2019-06-12 16:30 UTC
